### ISSUE TITLE
Deprecated numpy attribute

### ISSUE THREAD

**Issue by Kepser** [NevVerVer/neural-dynamics-gyration#1]
After installing the required packages using the requirements.txt file, an error is thrown when running the notebook code. Specifically, the mat73 package gives the AttributeError: module 'numpy' has no attribute 'typeDict'.

It turns out that this attribute was deprecated in numpy version 1.21.
What worked for me to solve the issue was to change the requirement from "numpy" to "numpy < 1.21"

**Comment by NevVerVer** [comment]
Thank you for finding this! Indeed, my working environment has version of numpy=='1.21.5' and mat73=='0.59'. I will upload new requirements with the versions of libraries to avoid such problems in the future :)
